### ISSUE TITLE
Device shadow service documents: "id" field is not documented.

### ISSUE THREAD

**Issue by leventov** [awsdocs/aws-iot-docs#16]
https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-document.html

At least `$aws/things/+/shadow/update/documents` topics should produce documents with `"id"` fields, but this is not documented anywhere.

**Comment by bobwatso-aws** [comment]
Thanks for the feedback!

AWS IoT doesn't send an `id` field in a shadow document unless a device included one. The [MQTT spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718039) does not allow publishing to a wildcard topic so, in the wildcard subscription example you describe, the thing name would be included in the topics of update document response messages published by AWS IoT. You would use that to identify the thing from which the document originated.

I've tested this a couple of ways and haven't seen an `id` field in a shadow document. If you have seen this, could you provide an example, please?

Thanks, again, for the feedback!

**Comment by leventov** [comment]
This is right, the id field appeared in lambda arguments serverless function had event defined as follows:
```
SELECT *, topic(3) as id from '$aws/things/+/shadow/update/documents'
```
It's where `id` was coming from.

**Comment by bobwatso-aws** [comment]
Thanks for the reply.
I'm glad you were able to identify the source of the field.
