### ISSUE TITLE
npm install, E404 Not Found

### ISSUE THREAD

**Issue by ufodriverr** [awsdocs/aws-iot-docs#23]
Install the AWS IoT Device SDK for JavaScript

Second part:
```
cd ~/aws-iot-device-sdk-js-v2
npm install
```

npm install gives:
```
E404
Not Found - GET https://registry.npmjs.org/@convergencelabs/typedoc-plugin-cusom-modules/-/typedoc-plugin-custom-modules-0.4.0.tgz

'@convergence/typedoc-plugin-custom-modules@0.4.0' is not in the npm registry.

etc...
```

**Comment by justinboswell** [comment]
That url it is trying to fetch looks like it has a typo in it (notice the cusom instead of custom). I have just verified that this works locally, can you try pulling again? I wonder if that module's npm config got broken temporarily.

**Comment by ufodriverr** [comment]
after i opened it in browser it worked from commands line O_O.
