### ISSUE TITLE
Cannot find index.js module when running the sample app

### ISSUE THREAD

**Issue by unknotsolutions** [awsdocs/aws-iot-docs#28]
When running the sample app using my iot endpoint,

`node dist\index.js --topic topic_1 --root-ca %USERPROFILE%\certs\Amazon-root-CA-1.pem --cert %USERPROFILE%\certs\device.pem.crt --key %USERPROFILE%\certs\private.pem.key --endpoint your-iot-endpoint`

I get an error as index.js cannot be found in _aws-iot-device-sdk-js-v2\samples\node\pub_sub\node_modules\aws-iot-device-sdk-v2\dist\_. In fact, there is no dist folder in my install.

**Comment by asavila** [comment]
Hi @unknotsolutions,

It looks like you might've missed steps 5-8 as detailed here: https://docs.aws.amazon.com/iot/latest/developerguide/using-laptop-as-device.html#gs-pc-sdk-node

Thank you,
Ashley
