### ISSUE TITLE
Documentation disagrees on the name for the refreshAfterInSecs/refreshAfterInSeconds value for custom authentication

### ISSUE THREAD

**Issue by timmattison** [awsdocs/aws-iot-docs#48]
One document says refreshAfterInSecs - https://github.com/awsdocs/aws-iot-docs/blame/master/developerguide/custom-authorizer.md#L29

Another document says refreshAfterInSeconds - https://github.com/awsdocs/aws-iot-docs/blame/master/developerguide/config-custom-auth.md#L60

Which is it?

**Comment by timmattison** [comment]
Ping

**Comment by gausekha** [comment]
I'll be updating the public docs today to mention refreshAfterInSeconds.

**Comment by gausekha** [comment]
Updated the docs: https://docs.aws.amazon.com/iot/latest/developerguide/custom-authorizer.html
