### ISSUE TITLE
MQTT wildcards instead of * wildcard used in examples

### ISSUE THREAD

**Issue by timmattison** [awsdocs/aws-iot-docs#49]
The documentation says that `+` and `#` wildcards are treated as literal values and that customers should use `*` wildcards.

https://github.com/awsdocs/aws-iot-docs/blame/7b216b17d6c51a45fba81ab566dc9bd7d46181ea/developerguide/pub-sub-policy.md#L228

However, immediately above this is an example of a topic filter with a `+` in it and it says:

```
For devices registered as things in the AWS IoT Core registry, the following policy grants permission to connect to AWS IoT Core with the client ID that matches the thing name, and to subscribe to the topic filter some/+/topic only:
```

Is this intended?

**Comment by liunamz-aws** [comment]
Hi, thanks for your feedback and apologies for the confusion.

I think the examples are correct, and we can modify the wording of that note to make it less confusing. 
For topic wildcards, take a look at the following article: 
https://docs.aws.amazon.com/iot/latest/developerguide/topics.html#topicfilters

**Comment by liunamz-aws** [comment]
Any updates? I think what the note means is as follows:

- Policies and MQTT interpret topic filter strings differently. 
- In MQTT subscription, `+` is treated as a wildcard for topic filter while in policies `+` is treated as a literal, not a wildcard.
- Attempts to subscribe to topic filters pattern `some/+/topic` are considered `some/{any string}/topic` by MQTT but only `some/+/topic` by policies, and in policies these attempts fail and cause the client to disconnect.

Please let us know if you have any questions.

**Comment by liunamz-aws** [comment]
Hello @timmattison FYI.

I added a table to the topic you pointed out for more clarification. The content will be published to public soon.

|Wildcard character | Is MQTT wildcard character | Example in MQTT | Is AWS IoT Core policy wildcard character | Example in AWS IoT Core policies for MQTT clients|
|-- | -- | -- | -- | --|
|# | Yes | some/# | No | N/A |
|+ | Yes | some/+/topic | No | N/A |
| * | No | N/A | Yes | topicfilter/some/*/topic|

Hope this will help. Thanks!

**Comment by liunamz-aws** [comment]
Hi, thanks again for your feedback. 
We have updated this topic [here](https://docs.aws.amazon.com/iot/latest/developerguide/pub-sub-policy.html). 

Closing this issue for now as it has been addressed.
Please reopen it when you think is needed.
