### ISSUE TITLE
Which topic should client subscribe to know a property of desired document become null?

### ISSUE THREAD

**Issue by tranduy216** [awsdocs/aws-iot-docs#54]
Hi AWS team,

Currently, client is using **/update/delta** to sync "reported" and "desired" document.
However, in case, a property of desired document become null, there is no message send to  **/update/delta**.
Could you guide me how the client know a property of desired document become null?

Thanks,

**Comment by gausekha** [comment]
Hi,

Thanks for the question. Your understanding is correct. When the desired value is set to null, the value should appear in the **/updated/documents** and **/updated/accepted** topics. Another suggestion to observe these changes would be to subscribe to the topic /update/# in the MQTT client. Using the wildcard would help observe the shadow behavior more clearly as updates to any of these topics would show up in the test client. An example of this use case is described in this document: https://docs.aws.amazon.com/iot/latest/developerguide/interact-lights-device-shadows.html

Please let me know if this helped answer your question. If you would like to learn more about the various MQTT reserved topics, please refer to this doc page: https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html.

**Comment by gausekha** [comment]
Hi,

I'm closing this issue based on the previous comment. Please feel free to reopen the issue if it didn't help answer your question.
