### ISSUE TITLE
Rename default branch from "master" to "main"

### ISSUE THREAD

**Issue by bobwatso-aws** [awsdocs/aws-iot-docs#55]
Rename the default branch to the more inclusive branch name, "main"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
