### ISSUE TITLE
[request] A specific guide from A to Z to setup secure tunneling

### ISSUE THREAD

**Issue by tomiszili** [awsdocs/aws-iot-docs#58]
Hi all!

It would be really nice to make a setup guide for the Secure Tunneling setup for example for a ubuntu based IoT device.
It is really hard to understand all the necessary steps to setup a tunnel for a device.
I guest the most effective way if you use a a dedicated EC2 instance for it, like a bastion host in a standard cloud environment.
This "bastion" EC2 shall be reached vie the Session Manager, and inside that host you should initiate a secure tunnel to a specific IoT device.

It would super helpfull to guide us from what and how should be installed on both the EC2 "bastion" and the IoT thing (Greengrass Core device), how to handle and store the tunnel tokens.
I will be grateful if only the easier method (source or destination) published.

Thanks in advance!

**Comment by gausekha** [comment]
Hi,

Thank you for the feedback and suggestion to help us improve the documentation. It makes sense to have such a valuable setup guide in the documentation, which will make it a nice walkthrough tutorial. 

We are always working to improve the documentation, and your feedback helps us know where to focus our efforts. 

Thanks!
-Gautham
