### ISSUE TITLE
Point out different handling of MQTT # wildcard in the "Differences from MQTT" section

### ISSUE THREAD

**Issue by jurijsteblaj** [awsdocs/aws-iot-docs#59]
Hi,

I think it would be appropriate to point out that AWS IoT handles # differently than the specification linked in the section [AWS IoT differences from MQTT version 3.1.1 specification](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html#mqtt-differences).

The [MQTT v3.1.1 specification](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718107) specifies "The multi-level wildcard represents the parent and any number of child levels." The topic filter "sport/#" should match the topic "sport". That is not the case with AWS IoT which does not match the parent topic.

While the way AWS IoT handles # is documented in [Topic filters](https://docs.aws.amazon.com/iot/latest/developerguide/topics.html#topicfilters) I think this difference from specification is worth mentioning in a bullet point in the "Differences from MQTT" section.

I would be willing to write this addition and make a PR if you give me the go-ahead.

**Comment by gausekha** [comment]
Hi,

Thank you for the feedback and for helping us improving the developer guide docs. I have added a bullet point in the [AWS IoT differences from MQTT version 3.1.1 specification](https://docs.aws.amazon.com/iot/latest/developerguide/mqtt.html#mqtt-differences) section of the page.

Thanks!
-Gautham

**Comment by jurijsteblaj** [comment]
That's great. Thanks!

Best regards
Jurij
