### ISSUE TITLE
A small clarification (Case statements)

### ISSUE THREAD

**Issue by m-menon** [awsdocs/aws-iot-docs#60]
Just ran into what seems to be a minor hiccup when setting up an AWS IoT rule. There is a value that I am evaluating and I need it to work this way

[Case statements](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-case.html)

If the value is
1) 0 then return 0
2) 1 then return 1
3) greater than 1 return 1
4) return null

something like this

> case someval
> 	WHEN 0 THEN 0
> 	WHEN 1 THEN 1
> 	WHEN (GREATER THAN 1) THEN 1
> 	ELSE null

But I am not sure what would be the right way to do this. I am trying something like this but not very sure if that's right ... cos if you see in the I am again checking for a condition down the line. it may evaluate that condition then compare with someval. That wouldn't give the correct result.

> case someval
> 	WHEN 0 THEN 0
> 	WHEN 1 THEN 1
> 	WHEN (someval > 1) THEN 1
> 	ELSE null

This should have been simpler but my SQL expertise is limited and in regular SQL I would have probably used an IIF (and immediate if or a ternary logic etc) or something

**Comment by bobwatso-aws** [comment]
Thanks for the note!

I dug into this and it turns out that the `WHEN value` value can only be a constant that is compared to the `CASE someval` variable. This is described in the current documentation, but not as clearly as it could be.
I'm in the process of updating that topic and it should be published soon.
Thanks, again, for identifying this.

**Comment by m-menon** [comment]
@bobwatso-aws , thanks for looking. Pls feel free to close the issue as you are already updating the topic.

**Comment by m-menon** [comment]
> Updated published topic at [Case statements](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sql-case.html). GitHub repo to be updated soon.

Would like to add a small suggestion - if it is feasible then it would be good to have the last updated/modified date on the AWS developer guide documentation. Simple as it might seem but at one glance it does give an idea if something's too old - especially AWS has a lot of documentation and there are times when one reads up quite a bit only to find that there is something newer,  or a better way of doing things. Older (doc) date will prompt users to check if there's something newer.

Thanks once again for updating the topic. Cheers.
