### ISSUE TITLE
AWS page not up to date with GitHub?

### ISSUE THREAD

**Issue by oaustegard** [awsdocs/aws-iot-docs#66]
See https://docs.aws.amazon.com/iot/latest/developerguide/secure-tunneling.html vs https://github.com/awsdocs/aws-iot-docs/blob/master/developerguide/secure-tunneling.md  The two texts are different.

Specifically there is a typo in the former that has been corrected on the latter : "secure tunneling does not require" vs "Secure tunneling does not require" (capitalization at start of sentence) but there are many additional differences.

¯\\_(ツ)\_/¯

**Comment by bobwatso-aws** [comment]
Thanks for the reminder!
I've updated the repo with the current documentation source.
