### ISSUE TITLE
Risk: over-authorization of AWS IoT policy

### ISSUE THREAD

**Issue by P-Verifier** [awsdocs/aws-iot-docs#70]
We are a security research team and we recently discovered that there is an over-authorization security issue with this project's IoT policies.
The affected files are as following:

	1. aws-iot-docs/developerguide/connect-iot-lorawan-create-destinations.md
	2. aws-iot-docs/developerguide/iot-dc-install-provision.md
	3. aws-iot-docs/developerguide/lightbulb-shadow-application.md
	4. aws-iot-docs/developerguide/connect-policy.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
