### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by Kamerabuilt** [awsdocs/aws-iot-docs#75]
Under the documentation page: 

https://docs.aws.amazon.com/iot/latest/developerguide/tagging-iot-iam.html 

It says: 
"Can't create a thing group the tag "env=prod" (in the example, see the line "aws:RequestTag/env" : "prod")."

It is missing 1 or more words for the sentence to be comprehensible. 

Perhaps you meant to say "Can't create a thing group and set the tag "env=prod" within the API request? 

Please correct the sentence accordingly, thank you.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
